<a href="https://colab.research.google.com/github/akshadtupe/Hello/blob/main/00_tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Baiscs of Tensorflow


In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
#Create A tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Dimension of tensor
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,2],
                     [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#Matrix with data type

matrix_2 = tf.constant([[0.,1.],
                        [2.,3.],
                        [4.,5.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float16)>

In [10]:
matrix_2.ndim

2

In [11]:
#creating  tensor
tensor= tf.constant([[[0,1,2],
                      [3,4,5],],
                     [[10,11,12],
                      [30,40,50]],
                     [[20,21,22],
                      [23,24,25]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [30, 40, 50]],

       [[20, 21, 22],
        [23, 24, 25]]], dtype=int32)>

\\#A tensor can have n no. of dimensions

In [14]:
#tf.variable
changeable_tensor = tf.Variable([1,2])
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [15]:
#asssigning values
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

In [16]:
#tensor with constant are imutable and Variable is mutable(using assign )

In [21]:
#creating Random tensors
random_1 = tf.random.Generator.from_seed(47)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(47)
random_2 = random_2.uniform(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.0876323 , -0.635568  ],
        [-0.6161736 , -1.9441465 ],
        [-0.48293006, -0.52447474]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.8139852 , 0.52180684],
        [0.12496924, 0.5488483 ],
        [0.7755773 , 0.6184403 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [26]:
### Shuffling elements in tensors
tensor_not_shuffled= tf.constant([[2,3],
                      [4,5],
                      [6,7]])
tf.random.shuffle(tensor_not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7],
       [4, 5]], dtype=int32)>

In [31]:
tf.random.set_seed(47)
tf.random.shuffle(tensor_not_shuffled,seed=47)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]], dtype=int32)>

In [33]:
import numpy as np
numpy_a= np.arange(1,13)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
#converting numpy array to tensor
numpy_tensor = tf.constant(numpy_a,shape=(2,6))
numpy_tensor

<tf.Tensor: shape=(2, 6), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>